version: "3.8"
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: cad_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    volumes:
      - ./backend/app:/app/app
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: cad_db
      MYSQL_HOST: db
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
 