version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/starfirecad
      - REDIS_URL=redis://cache:6379/0
      - SECRET_KEY=changeme
      - STRIPE_SECRET_KEY=sk_test_...
      - STRIPE_PUBLIC_KEY=pk_test_...
      - STRIPE_WEBHOOK_SECRET=whsec_...
      - DISCORD_BOT_TOKEN=token
    depends_on:
      - db
      - cache
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: starfirecad
    volumes:
      - pgdata:/var/lib/postgresql/data
  cache:
    image: redis:6

volumes:
  pgdata:
